### ISSUE TITLE
Please put the real wikimedia package on packagist.org

### ISSUE THREAD

**Issue by hboomsma** [JeroenDeDauw/mediawiki-fake-package#2]
mediawiki started using composer, your package on packagist.org prevents the community to put the real
package in and use it in a proper way.

https://github.com/wikimedia/mediawiki/blob/master/composer.json

**Comment by JeroenDeDauw** [comment]
Huh never saw this since I was not watching notifications on this repo...

This is done now https://packagist.org/packages/mediawiki/core

**Comment by hboomsma** [comment]
Thnx!
